version: '3.8'

services:

  web:
    container_name: web
    build: .
    volumes:
      - .:/app
    env_file:
      - ./app/.env
    ports:
      - "33000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    expose:
      - 5432

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
    postgres_data:
